# Feature Engineering. Практическая работа

Сдаётся на проверку.

## Цели практической работы

Научиться: 

*   генерировать новые признаки; 
*   нормализовать и кодировать данные с помощью lambda-функций и библиотеки scikit-learn.

## Что входит в практическую работу

1. Построить признаки из строк.
2. Преобразовать категориальные переменные.
3. Стандартизировать данные.
4. Использовать MinMaxScaler для нормализации данных.
5. Создать признаки на основе дат.
6. Сохранить датафрейм для этапа моделирования.

## Что оценивается
- Программа выдаёт верный ответ на заданном наборе данных.
- Описаны причины выбранного решения, если требуется.
- Код читабелен: переменным даны осмысленные названия, соблюдены отступы и правила расстановки пробелов.
- При построении графиков название и оси подписаны, выведена легенда, если требуется. 
- Репозиторий проекта содержит осмысленные коммиты, содержащие конкретные реализованные фичи, ветки названы согласно назначению, лишние файлы не хранятся в репозитории.
- В репозитории проекта соблюдена иерархия директорий согласно списку модулей и содержащихся в них тем.
- Репозиторий проекта содержит файлы с данными, полученными в результате выполнения практической работы.

## Как отправить работу на проверку
Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему проверяющему куратору.

## Задача

Мы продолжим исследовать и готовить данные для этапа моделирования.

Вам предстоит работать с небольшой выборкой из коллекции подержанных автомобилей, выставленных на продажу в Соединённых Штатах, представленной в файле `data/vehicles_dataset_upd.csv`. На этих данных вы построите первую модель классификации, определяющую категорию цены подержанного автомобиля в зависимости от характеристик транспортного средства.

В этой практической работе вы продолжите генерировать дополнительные признаки и завершите подготовку датасета для этапа моделирования.

## Описание датасета:
- `id`— идентификатор записи;
- `url`— URL-записи о продаже;
- `region`— регион;
- `region_url`— URL региона;
- `price`— стоимость;
- `year`— год выпуска;
- `manufacturer`— производитель;
- `model`— модель;
- `condition`— состояние;
- `cylinders`— количество цилиндров;
- `fuel`— тип топлива;
- `odometer`— количество пройденных миль;
- `title_status`— статус;
- `transmission`— коробка передач;
- `VIN`— идентификационный номер;
- `drive`— тип привода;
- `size`— размер;
- `type`— кузов;
- `paint_color`— цвет;
- `image_url`— URL изображения;
- `description`— указанное описание;
- `county`— страна;
- `state`— штат;
- `lat`— широта;
- `long`— долгота;
- `posting_date`— дата размещения объявления о продаже;
- `price_category`— категория цены.

In [981]:
import pandas as pd

### Задача 1. Построение признаков из строк

1. Загрузите датасет из `data/vehicles_dataset_upd6.csv`, выведите первые пять записей и список колонок.

In [982]:
df = pd.read_csv('vehicles_dataset_upd6.csv')
print(df.head())
print(df.columns)

           id                                                url  \
0  7308295377  https://chattanooga.craigslist.org/ctd/d/chatt...
1  7316380095  https://newjersey.craigslist.org/ctd/d/carlsta...
2  7313733749  https://reno.craigslist.org/ctd/d/atlanta-2017...
3  7308210929  https://fayetteville.craigslist.org/ctd/d/rale...
4  7303797340  https://knoxville.craigslist.org/ctd/d/knoxvil...

         region                           region_url  price  year  \
0   chattanooga   https://chattanooga.craigslist.org  54990  2020
1  north jersey     https://newjersey.craigslist.org  16942  2016
2  reno / tahoe          https://reno.craigslist.org  35590  2017
3  fayetteville  https://fayetteville.craigslist.org  14500  2013
4     knoxville     https://knoxville.craigslist.org  14590  2012

  manufacturer                   model    fuel  odometer  ...  \
0          ram  2500 crew cab big horn  diesel     27442  ...
1         ford    explorer 4wd 4dr xlt   other     60023  ...
2   volkswagen        golf r hatchback     gas     14048  ...
3       toyota                    rav4     gas    117291  ...
4          bmw  1 series 128i coupe 2d   other     80465  ...

             manufacturer_model desc_len model_in_desc x0_diesel x0_electric  \
0   ram: 2500 crew cab big horn     4482             0       1.0         0.0
1    ford: explorer 4wd 4dr xlt      968             0       0.0         0.0
2  volkswagen: golf r hatchback     4286             0       0.0         0.0
3                  toyota: rav4     3241             0       0.0         0.0
4   bmw: 1 series 128i coupe 2d     4851             0       0.0         0.0

   x0_gas  x0_hybrid x0_other std_scaled_odometer std_scaled_price
0     0.0        0.0      0.0           -1.079390         2.958509
1     0.0        0.0      1.0           -0.560115        -0.085826
2     1.0        0.0      0.0           -1.292863         1.406256
3     1.0        0.0      0.0            0.352621        -0.281218
4     0.0        0.0      1.0           -0.234311        -0.274017

[5 rows x 34 columns]
Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'fuel', 'odometer', 'title_status', 'transmission',
       'image_url', 'description', 'state', 'lat', 'long', 'posting_date',
       'price_category', 'date', 'odometer_km', 'odometer/price', 'region_new',
       'region_corrected', 'manufacturer_model', 'desc_len', 'model_in_desc',
       'x0_diesel', 'x0_electric', 'x0_gas', 'x0_hybrid', 'x0_other',
       'std_scaled_odometer', 'std_scaled_price'],
      dtype='object')

2. Выведите список значений и количество уникальных значений для модели автомобиля.

In [983]:
print(df['model'].unique())
print(df['model'].nunique())

['2500 crew cab big horn' 'explorer 4wd 4dr xlt' 'golf r hatchback' ...
 'gs350' '1988 Nisan' 'a3 2.0t premium plus pzev']
3341

3. Количество уникальных значений велико. Попробуем их сократить, оставив только первое слово в наименовании модели. С помощью lambda-функции и преобразования над строками создайте новый признак `short_model`, содержащий только первое слово из наименования модели, выведите его и количество получившихся уникальных значений.

In [984]:
df['short_model'] = df['model'].apply(lambda x: str(x).split()[0])
print(df['short_model'].head())
print(df['short_model'].nunique())

0        2500
1    explorer
2        golf
3        rav4
4           1
Name: short_model, dtype: object
943

### Задача 2. Преобразование категориальных переменных

1. Для категориальных переменных `short_model`, `transmission`, `region`, `manufacturer`, `state`, `title_status`, `age_category` распечатайте наименование категории и количество уникальных значений в ней.

In [985]:
def cat_age(year):
    if year >= 2020:
        return 'new'
    elif year >= 2010:
        return 'modern'
    else:
        return 'old'

df['age_category'] = df['year'].apply(cat_age)


columns_to_encode = ['short_model', 'transmission', 'region', 'manufacturer', 'state', 'title_status', 'age_category']

for col in columns_to_encode:
    if col in df.columns:
        print(f"Категория: {col}")
        print(f"Количество уникальных: {df[col].nunique()}")
        print("-" * 30)

Категория: short_model
Количество уникальных: 943
------------------------------
Категория: transmission
Количество уникальных: 3
------------------------------
Категория: region
Количество уникальных: 393
------------------------------
Категория: manufacturer
Количество уникальных: 40
------------------------------
Категория: state
Количество уникальных: 51
------------------------------
Категория: title_status
Количество уникальных: 6
------------------------------
Категория: age_category
Количество уникальных: 3
------------------------------

2. Создайте датафрейм `data`, содержащий только выбранные категориальные переменные.

In [986]:
df['model_len'] = df['model'].apply(len)

df['model_word_count'] = df['model'].apply(lambda x: len(str(x).split()))

columns_to_encode = [
    'short_model', 
    'transmission', 
    'region', 
    'manufacturer', 
    'state', 
    'title_status', 
    'age_category', 
    'model_len', 
    'model_word_count'
]

data = df[columns_to_encode]
data.head()

,short_model,transmission,region,manufacturer,state,title_status,age_category,model_len,model_word_count
0,2500,other,chattanooga,ram,tn,clean,new,22,5
1,explorer,automatic,north jersey,ford,nj,clean,modern,20,4
2,golf,other,reno / tahoe,volkswagen,ca,clean,modern,16,3
3,rav4,automatic,fayetteville,toyota,nc,clean,modern,4,1
4,1,other,knoxville,bmw,tn,clean,modern,22,5

3. Создайте объект класса OneHotEncoder, который будет отвечать за преобразование. Уточните, что на выходе должна быть неразреженная матрица.

In [987]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)

4. Идентифицируйте параметры преобразования на датафрейме с категориальными переменными.

In [988]:
ohe_data = ohe.fit_transform(data)

ohe_df = pd.DataFrame(ohe_data, columns=ohe.get_feature_names_out())

5. Примените преобразование для датафрейма с категориальными переменными и сохраните в новую переменную, распечатайте получившуюся матрицу и её размерность.

In [989]:
print("Размерность матрицы:", ohe_data.shape)
print(ohe_data[:5])

Размерность матрицы: (9619, 1525)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]

6. Выведите новые наименования признаков с помощью метода `get_feature_names_out`.

In [990]:
ohe.get_feature_names_out()

array(['short_model_-benz', 'short_model_1', 'short_model_124', ...,
       'model_word_count_24', 'model_word_count_27',
       'model_word_count_29'], shape=(1525,), dtype=object)

7. Добавьте в исходный датафрейм получившиеся новые признаки, выведите первые пять записей датафрейма и список колонок.

In [991]:
df_new = pd.concat([df.reset_index(drop=True), ohe_df], axis=1)

print(df_new.head())
print("\nСписок всех колонок после объединения:")
print(df_new.columns.tolist())

           id                                                url  \
0  7308295377  https://chattanooga.craigslist.org/ctd/d/chatt...
1  7316380095  https://newjersey.craigslist.org/ctd/d/carlsta...
2  7313733749  https://reno.craigslist.org/ctd/d/atlanta-2017...
3  7308210929  https://fayetteville.craigslist.org/ctd/d/rale...
4  7303797340  https://knoxville.craigslist.org/ctd/d/knoxvil...

         region                           region_url  price  year  \
0   chattanooga   https://chattanooga.craigslist.org  54990  2020
1  north jersey     https://newjersey.craigslist.org  16942  2016
2  reno / tahoe          https://reno.craigslist.org  35590  2017
3  fayetteville  https://fayetteville.craigslist.org  14500  2013
4     knoxville     https://knoxville.craigslist.org  14590  2012

  manufacturer                   model    fuel  odometer  ...  \
0          ram  2500 crew cab big horn  diesel     27442  ...
1         ford    explorer 4wd 4dr xlt   other     60023  ...
2   volkswagen        golf r hatchback     gas     14048  ...
3       toyota                    rav4     gas    117291  ...
4          bmw  1 series 128i coupe 2d   other     80465  ...

  model_word_count_12 model_word_count_13 model_word_count_14  \
0                 0.0                 0.0                 0.0
1                 0.0                 0.0                 0.0
2                 0.0                 0.0                 0.0
3                 0.0                 0.0                 0.0
4                 0.0                 0.0                 0.0

  model_word_count_15 model_word_count_17  model_word_count_21  \
0                 0.0                 0.0                  0.0
1                 0.0                 0.0                  0.0
2                 0.0                 0.0                  0.0
3                 0.0                 0.0                  0.0
4                 0.0                 0.0                  0.0

   model_word_count_22 model_word_count_24 model_word_count_27  \
0                  0.0                 0.0                 0.0
1                  0.0                 0.0                 0.0
2                  0.0                 0.0                 0.0
3                  0.0                 0.0                 0.0
4                  0.0                 0.0                 0.0

  model_word_count_29
0                 0.0
1                 0.0
2                 0.0
3                 0.0
4                 0.0

[5 rows x 1563 columns]

Список всех колонок после объединения:

8. Посмотрите на результат обратного преобразования получившейся матрицы в исходные признаки, используйте `inverse_transform`.

In [992]:
inverse_data = ohe.inverse_transform(ohe_data)
print(inverse_data[:5])

[['2500' 'other' 'chattanooga' 'ram' 'tn' 'clean' 'new' 22 5]
 ['explorer' 'automatic' 'north jersey' 'ford' 'nj' 'clean' 'modern' 20 4]
 ['golf' 'other' 'reno / tahoe' 'volkswagen' 'ca' 'clean' 'modern' 16 3]
 ['rav4' 'automatic' 'fayetteville' 'toyota' 'nc' 'clean' 'modern' 4 1]
 ['1' 'other' 'knoxville' 'bmw' 'tn' 'clean' 'modern' 22 5]]

### Задача 3. Стандартизация данных

1. Создайте переменную под количественные переменные `lat`, `long`, `year`, `odometer/price`, `desc_len`, `model_in_desc`, `model_len`, `model_word_count` и создайте датафрейм `data`, содержащий только выбранные количественные переменные.

In [993]:
df['model_len'] = df['model'].apply(lambda x: len(str(x)))

df['model_word_count'] = df['model'].apply(lambda x: len(str(x).split()))

if 'odometer/price' not in df.columns:
    df['odometer/price'] = df['odometer'] / df['price']

In [994]:
num_columns = ['lat', 'long', 'year', 'odometer/price', 'desc_len', 'model_in_desc', 'model_len', 'model_word_count']

data_std = df[num_columns]
data_std.head()

,lat,long,year,odometer/price,desc_len,model_in_desc,model_len,model_word_count
0,35.060000,-85.250000,2020,0.499036,4482,0,22,5
1,40.821805,-74.061962,2016,3.542852,968,0,20,4
2,33.779214,-84.411811,2017,0.394718,4286,0,16,3
3,35.715954,-78.655304,2013,8.089034,3241,0,4,1
4,35.970000,-83.940000,2012,5.515079,4851,0,22,5

2. Создайте объект `std_scaler` класса StandardScaler с параметрами по умолчанию, который будет отвечать за стандартизацию.

In [995]:
std_scaler.fit(df[num_columns])
df_std = std_scaler.transform(df[num_columns])

3. Идентифицируйте параметры преобразования на датафрейме с количественными переменными.

In [996]:
df_std_scaled = pd.DataFrame(df_std, columns=std_scaler.get_feature_names_out())
df_result = pd.concat([df_new.reset_index(drop=True), df_std_scaled], axis=1)

4. Примените преобразование для датафрейма с количественными переменными и сохраните в новую переменную, распечатайте получившуюся матрицу и её размерность.

In [997]:
print(df_result.shape)

(9619, 1571)

5. Создайте наименования новых признаков по шаблону: `lat_std` для `lat` и так далее.

In [998]:
std_cols = [f"{col}_std" for col in num_columns]
print(std_cols)

['lat_std', 'long_std', 'year_std', 'odometer/price_std', 'desc_len_std', 'model_in_desc_std', 'model_len_std', 'model_word_count_std']

6. Добавьте в исходный датафрейм получившиеся новые признаки, выведите первые пять записей датафрейма и список колонок.

In [999]:
df_result = pd.concat([df_new.reset_index(drop=True), df_std_scaled], axis=1)

print(df_result.head())

print(df_result.columns.tolist())

           id                                                url  \
0  7308295377  https://chattanooga.craigslist.org/ctd/d/chatt...
1  7316380095  https://newjersey.craigslist.org/ctd/d/carlsta...
2  7313733749  https://reno.craigslist.org/ctd/d/atlanta-2017...
3  7308210929  https://fayetteville.craigslist.org/ctd/d/rale...
4  7303797340  https://knoxville.craigslist.org/ctd/d/knoxvil...

         region                           region_url  price  year  \
0   chattanooga   https://chattanooga.craigslist.org  54990  2020
1  north jersey     https://newjersey.craigslist.org  16942  2016
2  reno / tahoe          https://reno.craigslist.org  35590  2017
3  fayetteville  https://fayetteville.craigslist.org  14500  2013
4     knoxville     https://knoxville.craigslist.org  14590  2012

  manufacturer                   model    fuel  odometer  ...  \
0          ram  2500 crew cab big horn  diesel     27442  ...
1         ford    explorer 4wd 4dr xlt   other     60023  ...
2   volkswagen        golf r hatchback     gas     14048  ...
3       toyota                    rav4     gas    117291  ...
4          bmw  1 series 128i coupe 2d   other     80465  ...

  model_word_count_27 model_word_count_29       lat      long      year  \
0                 0.0                 0.0 -0.619172  0.484245  1.322394
1                 0.0                 0.0  0.388014  1.110800  0.695973
2                 0.0                 0.0 -0.843059  0.531185  0.852578
3                 0.0                 0.0 -0.504509  0.853562  0.226157
4                 0.0                 0.0 -0.460101  0.557607  0.069552

   odometer/price  desc_len model_in_desc model_len model_word_count
0       -0.510784  0.632075     -0.155788  1.163032         1.911041
1       -0.402947 -0.646781     -0.155788  0.932087         1.236064
2       -0.514480  0.560744     -0.155788  0.470197         0.561088
3       -0.241883  0.180435     -0.155788 -0.915473        -0.788864
4       -0.333074  0.766366     -0.155788  1.163032         1.911041

[5 rows x 1571 columns]

### Задача 4. MinMax-нормализация данных

1. Импортируйте MinMaxScaler из `sklearn.preprocessing`.

In [1000]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

2. Создайте датафрейм, содержащий переменные `lat` и `long`.

In [1001]:
data_mm = df[['lat', 'long']]

std_scaler = StandardScaler()
df_std = pd.DataFrame(std_scaler.fit_transform(data_mm), columns=['lat_std', 'long_std'])

3. Повторите действия пунктов 2–6 из задачи 3 для добавления в исходный датафрейм признаков `lat_mm` и `long_mm`. Выведите получившийся датафрейм.

In [1002]:
mm_scaler = MinMaxScaler()
df_mm = pd.DataFrame(mm_scaler.fit_transform(data_mm), columns=['lat_mm', 'long_mm'])

df_result = pd.concat([
    df[['lat', 'long']].reset_index(drop=True),
    df_std.reset_index(drop=True),
    df_mm.reset_index(drop=True)
], axis=1)

df_result[['lat', 'lat_std', 'lat_mm', 'long', 'long_std', 'long_mm']].head()

         lat   lat_std    lat_mm       long  long_std   long_mm
0  35.060000 -0.619172  0.341769 -85.250000  0.484245  0.288699
1  40.821805  0.388014  0.468665 -74.061962  1.110800  0.333055
2  33.779214 -0.843059  0.313561 -84.411811  0.531185  0.292022
3  35.715954 -0.504509  0.356215 -78.655304  0.853562  0.314844
4  35.970000 -0.460101  0.361810 -83.940000  0.557607  0.293893

4. Создайте переменную под географические признаки `lat`, `lat_std`, `lat_mm`, `long`, `long_std`, `long_mm` и выведите их. Посмотрите на различия в значениях для исходных признаков и нормализованных с помощью стандартизации и MinMax-преобразования.

In [1003]:
geo_columns = ['lat', 'lat_std', 'lat_mm', 'long', 'long_std', 'long_mm']
print(df_result[geo_columns].head())

         lat   lat_std    lat_mm       long  long_std   long_mm
0  35.060000 -0.619172  0.341769 -85.250000  0.484245  0.288699
1  40.821805  0.388014  0.468665 -74.061962  1.110800  0.333055
2  33.779214 -0.843059  0.313561 -84.411811  0.531185  0.292022
3  35.715954 -0.504509  0.356215 -78.655304  0.853562  0.314844
4  35.970000 -0.460101  0.361810 -83.940000  0.557607  0.293893

5. Выведите описательные статистики для всех географических признаков. Посмотрите на различия в статистиках для исходных признаков и нормализованных с помощью стандартизации и MinMax-преобразования.

In [1004]:
print(df_result[geo_columns].describe())

               lat       lat_std       lat_mm         long      long_std  \
count  9619.000000  9.619000e+03  9619.000000  9619.000000  9.619000e+03
mean     38.602095  2.068323e-16     0.419779   -93.896875 -4.520763e-16
std       5.720989  1.000052e+00     0.125997    17.857352  1.000052e+00
min      19.541726 -3.331829e+00     0.000000  -158.069300 -3.593801e+00
25%      34.920000 -6.436450e-01     0.338685  -106.944340 -7.306875e-01
50%      39.300000  1.219966e-01     0.435149   -87.845800  3.388739e-01
75%      42.382100  6.607601e-01     0.503028   -80.678711  7.402470e-01
max      64.947500  4.605283e+00     1.000000    94.163200  1.053179e+01

           long_mm
count  9619.000000
mean      0.254418
std       0.070797
min       0.000000
25%       0.202690
50%       0.278408
75%       0.306822
max       1.000000

6. Выведите матрицу корреляций для всех географических признаков, чтобы убедиться, что нормализация признаков сохранила свойства исходных признаков.

In [1005]:
print(df_result[geo_columns].corr())

               lat   lat_std    lat_mm      long  long_std   long_mm
lat       1.000000  1.000000  1.000000 -0.134596 -0.134596 -0.134596
lat_std   1.000000  1.000000  1.000000 -0.134596 -0.134596 -0.134596
lat_mm    1.000000  1.000000  1.000000 -0.134596 -0.134596 -0.134596
long     -0.134596 -0.134596 -0.134596  1.000000  1.000000  1.000000
long_std -0.134596 -0.134596 -0.134596  1.000000  1.000000  1.000000
long_mm  -0.134596 -0.134596 -0.134596  1.000000  1.000000  1.000000

### Задача 5. Признаки на основе дат

1. Выведите по отдельности колонки `posting_date` и `date`.

In [1006]:
print(df[['posting_date', 'date']].head())

               posting_date                       date
0  2021-04-17T12:30:50-0400  2021-04-17 16:30:50+00:00
1  2021-05-03T15:40:21-0400  2021-05-03 19:40:21+00:00
2  2021-04-28T03:52:20-0700  2021-04-28 10:52:20+00:00
3  2021-04-17T10:08:57-0400  2021-04-17 14:08:57+00:00
4  2021-04-08T15:10:56-0400  2021-04-08 19:10:56+00:00

2. Ранее преобразованная колонка `date` после сохранения в файл и загрузки из него содержит данные в строковом формате, поэтому измените её тип c помощью `pd.to_datetime`.

In [1007]:
df['date'] = pd.to_datetime(df['date'])

print(df['date'].dtype)

datetime64[ns, UTC]

3. Несколькими способами извлеките номер месяца продажи автомобиля.

3.1. Из переменной `posting_date` с помощью lambda-функции и операций над строками.

In [1008]:

df['month_lambda_str'] = df['posting_date'].apply(lambda x: int(x[5:7]))
print(df['month_lambda_str'].head())

0    4
1    5
2    4
3    4
4    4
Name: month_lambda_str, dtype: int64

3.2. Из переменной `date` с помощью lambda-функции и метода `month`.

In [1009]:
df['month_lambda_date'] = df['date'].apply(lambda x: x.month)
print(df['month_lambda_date'].head())

0    4
1    5
2    4
3    4
4    4
Name: month_lambda_date, dtype: int64

3.3. Из переменной `date` с помощью `dt` и метода `month`.

In [1010]:
df['month'] = df['date'].dt.month
print(df['month'].head())

0    4
1    5
2    4
3    4
4    4
Name: month, dtype: int32

4. Создайте любым из способов (3.2 или 3.3) признак `month`, обозначающий номер месяца размещения объявления о продаже автомобиля, и распечатайте его.

In [1011]:
print(df['month'].value_counts())

month
4    6974
5    2645
Name: count, dtype: int64

5. Создайте признак `dayofweek`, обозначающий день недели размещения объявления о продаже автомобиля, и распечатайте его.

In [1012]:
df['dayofweek'] = df['date'].dt.dayofweek
print(df['dayofweek'].head())

0    5
1    0
2    2
3    5
4    3
Name: dayofweek, dtype: int32

6. Создайте признак `diff_years`, обозначающий количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля, и распечатайте его. Дополнительные корректировки не применяйте.

In [1013]:
df['diff_years'] = df['date'].dt.year - df['year']
print(df['diff_years'].head())

0    1
1    5
2    4
3    8
4    9
Name: diff_years, dtype: int64

7. Примените стандартизацию к новым признаками и сохраните результат в новые признаки вида `month_std`.

In [1014]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

month_std = std_scaler.fit_transform(df[['month']])

df['month_std'] = month_std

print(df[['month', 'month_std']].head())

   month  month_std
0      4  -0.615846
1      5   1.623784
2      4  -0.615846
3      4  -0.615846
4      4  -0.615846

### Задача 6. Сохранение датафрейма для этапа моделирования

1. Удалите колонки, которые были исходными для формирования признаков, а также новые признаки, которые были добавлены с целью обучения.  Сохраните новый датафрейм в переменную `df_prepared`.

In [1015]:
df_result = pd.concat([
    df_result.reset_index(drop=True),
    ohe_df.reset_index(drop=True)    
], axis=1)

print(f"Размер перед очисткой: {df_result.shape}")


columns_for_drop = [
    'year', 'region', 'manufacturer', 'model', 'fuel', 'odometer', 'title_status', 
    'transmission', 'state', 'lat', 'long', 'region_corrected', 'manufacturer_model', 
    'desc_len', 'model_in_desc', 'price_k$', 'age_category', 'model_len', 
    'model_word_count', 'short_model', 'date', 'diff_years'
]


df_prepared = df_result.drop(columns=columns_for_drop, errors='ignore')

Размер перед очисткой: (9619, 1531)

2. Распечатайте оставшийся список колонок и размерность финального датафрейма.

In [1016]:
print(f"Размерность финального датафрейма: {df_prepared.shape}")

Размерность финального датафрейма: (9619, 1529)

3. Запишите преобразованный датафрейм в файл `data/vehicles_dataset_prepared.csv`, индекс не сохраняйте.

In [1017]:
df_prepared.to_csv('vehicles_dataset_prepared.csv', index=False)
print("Файл успешно сохранен в 'data/vehicles_dataset_prepared.csv'")

Файл успешно сохранен в 'data/vehicles_dataset_prepared.csv'

## Описание преобразованного датасета:
- `id`— идентификатор записи;
- `is_manufacturer_name`— признак производителя автомобиля;

- `region_*`— регион;
- `x0_*`— тип топлива;
- `manufacturer_*`— производитель;
- `short_model_*`— сокращённая модель автомобиля;
- `title_status_*`— статус;
- `transmission_*`— коробка передач;
- `state_*`— штат;
- `age_category_*`— возрастная категория автомобиля;

- `std_scaled_odometer`— количество пройденных миль (после стандартизации);
- `year_std`— год выпуска (после стандартизации);
- `lat_std`— широта (после стандартизации);
- `long_std`— долгота (после стандартизации);
- `odometer/price_std`— отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`— количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`— количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`— длина наименования автомобиля (после стандартизации);
- `model_word_count_std`— количество слов в наименовании автомобиля (после стандартизации);
- `month_std`— номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`— день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`— количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`— стоимость;
- `price_category`– категория цены.

In [1018]:
print(df_result.shape)

(9619, 1531)